### ISSUE TITLE
Add link to contact form

### ISSUE THREAD

**Issue by TorstenStueber** [pendulum-chain/playground#43]
Add a footer with a link to `github.com/pendulum-chain/`.

The link text should be "Contact". The footer should be visible on every page.

**Comment by gonzamontiel** [comment]
I did as requested, it looks a bit ugly without anything else. Should we add twiiter or other links? A copyright?

**Comment by TorstenStueber** [comment]
Sorry, my bad. I actually meant a link to `https://pendulumchain.org/newsletter` instead. I will change it in the code.
