### ISSUE TITLE
Add social links to the playground

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/playground#47]
## Description
The playground must have links to the official social handles of Pendulum.
Here are the respective links
- Twitter:- https://twitter.com/pendulum_chain
- Medium:- https://pendulum-chain.medium.com/
- Telegram:- https://t.me/pendulum_chain
- Discord:- https://discord.com/invite/NBGVC75Fsf
- Newsletter:- https://pendulumchain.org/newsletter

## Fonts required
- Twitter:- https://fontawesome.com/v5.15/icons/twitter?style=brands
- Medium - https://fontawesome.com/v5.15/icons/medium?style=brands
- Telegram - https://fontawesome.com/v5.15/icons/telegram?style=brands
- Discord - https://fontawesome.com/v5.15/icons/discord?style=brands
- Newsletter - https://fontawesome.com/v5.15/icons/envelope-open-text?style=solid

These icons can either be added alongside the github icon or at the bottom of the playground page.

**Comment by gonzamontiel** [comment]
Icons already merged. Closing this ticket.
